#!/usr/bin/python3

#  Copyright (C) 2014, 2018  Rafael Senties Martinelli
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.

import os
import sys

__version__ = '18.01.06'

argserror='''
 This script deletes (recursively) the backup files created by bluefish.

	** WARNING ** : All the files ending by a "~" will be deleted.

 You can use it in two different ways:

	1) By Calling the script without a path argument, and it will work in the current directory.
	2) By adding a path as argument, and it will work on the path.
 
	* You can add a '-pyc' argument to delete *pyc files too.
 
 Examples:
 
	delete-backups -pyc
	delete-backups /home/
	delete-backups /home/ -pyc
 
'''
	
def delete_files(path, pyc):
	
	if pyc:
		list=[os.path.join(dp, f) for dp, dn, filenames in os.walk(path) for f in filenames if f[-1:] == '~' or f[-3:]=='pyc']
	else:
		list=[os.path.join(dp, f) for dp, dn, filenames in os.walk(path) for f in filenames if f[-1:] == '~']
	
	
	i=0
	error=0
	p=0
	for file in list:
		try:
			os.remove(file)
			
			if file[-1:] == '~':
				i+=1
			elif file[-3:]=='pyc':
				p+=1
			
		except:
			error+=1
	
	if error==0:
		if pyc:
			print("del-backups: {0} backup and {1} pyc files went deleted.".format(i,p))
		else:
			print("del-backups: {0} backup files went deleted.".format(i))
			
	elif error>0:
		if pyc:
			print('''del-backups: {0} backupfiles and {1} pyc files went deleted. went deleted, but {2} couln't be deleted.
You may not be the owner of this files.'''.format(i,p,error))

		else:
			print('''del-backups: {0} backupfiles files went deleted. went deleted, but {1} couln't be deleted.
You may not be the owner of this files.'''.format(i,error))


if __name__ == "__main__":
	
	total=len(sys.argv)

	if total==1:
		delete_files(os.getcwd(),False)
	
	elif total==2:
		arg2=str(sys.argv[1])
		
		if arg2=='-pyc':
			delete_files(os.getcwd(), True)
		else:		
			if os.path.exists(arg2):
				if os.path.isdir(arg2):
					delete_files(arg2, False)
				else:
					print("The path that you entered is not a directory")
			else:
				print("The path that you entered doesn't exists \n"+argserror)
	
	elif total==3:
		
		arg2=str(sys.argv[1])
		arg3=str(sys.argv[2])
		
		if arg3!='-pyc':
			print(argserror)
		else:
			if os.path.exists(arg2):
				if os.path.isdir(arg2):
					delete_files(arg2, True)
				else:
					print("The path that you entered is not a directory")
			else:
				print("The path that you entered doesn't exists \n"+argserror)
	else:
		print(argserror)
